# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('job_id', models.CharField(blank=True, max_length=128, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('started_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
