# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('mail_from', models.EmailField(max_length=254)),
                ('mail_to', models.TextField()),
                ('cc', models.TextField()),
                ('bcc', models.TextField()),
                ('body_type', models.CharField(choices=[('plain', 'plain text'), ('html', 'HTML')], max_length=32)),
            ],
        ),
    ]
