# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
