# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0003_auto_20161007_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='body_type',
            field=models.CharField(choices=[('plain', 'plain text'), ('html', 'HTML')], default='plain', max_length=32),
        ),
    ]
