# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0005_auto_20161007_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionlist',
            name='emails',
        ),
        migrations.AddField(
            model_name='distributionlist',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionlist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='distribution_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mail.DistributionList'),
            preserve_default=False,
        ),
    ]
