# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0007_mailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mail_from', models.EmailField(max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('distribution_list_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.DistributionList')),
                ('mail_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.MailTemplate')),
            ],
        ),
        migrations.AlterField(
            model_name='mail',
            name='bcc',
            field=models.TextField(blank=True, help_text='Enter a list of bcc separated with commas (,)', null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cc',
            field=models.TextField(blank=True, help_text='Enter a list of cc separated with commas (,)', null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_to',
            field=models.TextField(help_text='Enter a list of receipients separated with commas (,)'),
        ),
    ]
