# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_auto_20161011_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.FileField(upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='massmail',
            name='mail_from',
        ),
        migrations.AddField(
            model_name='mail',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='mail_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='mail_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.MailTemplate'),
        ),
    ]
