# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_auto_20161018_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailattachment',
            name='content_type',
            field=models.CharField(default='text/plain', max_length=128),
        ),
        migrations.AlterField(
            model_name='distributionlist',
            name='name',
            field=models.CharField(help_text='Please enter a name for this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='name',
            field=models.CharField(help_text='Please enter a name for this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='content',
            field=models.FileField(help_text='Pick a file to use as the content of this mail attachment', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='name',
            field=models.CharField(help_text='Please enter a name for this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='body',
            field=models.TextField(help_text='Enter the body of this template - can be either plain text or html depending on body type'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='mail_from',
            field=models.EmailField(blank=True, help_text='Enter a mail from - you may leave it empty to use the default mail from', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='name',
            field=models.CharField(help_text='Please enter a name for this object', max_length=128),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='reply_to',
            field=models.EmailField(blank=True, help_text='Enter an optional reply to email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.TextField(help_text='Enter the subject of this template'),
        ),
    ]
