# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_auto_20161018_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.MailTemplate'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
