# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_auto_20161214_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_to',
            field=models.TextField(blank=True, help_text='Enter a list of receipients separated with commas (,)', null=True),
        ),
    ]
