# Generated by Django 3.1.1 on 2020-09-09 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0013_auto_20190626_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='distribution_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.distributionlist'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.mailtemplate'),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='content',
            field=models.FileField(help_text='Pick a file to use as the content of this mail attachment', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='mail_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.mailtemplate'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='massmail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='massmail',
            name='distribution_list_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.distributionlist'),
        ),
        migrations.AlterField(
            model_name='massmail',
            name='mail_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.mailtemplate'),
        ),
    ]
