# Generated by Django 3.1.1 on 2020-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_auto_20200909_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='attachments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
